site_name: Coding
site_url: https://jasper-zanjani.github.io/coding
theme:
  name: material
  favicon: img/logo.png
  logo: img/logo.png
  palette:
    scheme: slate
    primary: pink
    accent: pink
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
extra_css:
- style/annotation-width.css
plugins:
- search
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - meta
  - pymdownx.details
  - pymdownx.emoji: # from https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#emoji
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
# MathJax
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
- javascripts/mathjax.js
- https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

